/* Developed by Akash Mani - This site is developed by Akash Mani. Original watermark of Akash Mani. */
// Auto-generated 300 Problem DSA Sheet Data - Highly Curated Placement Mapping
import { Problem } from './types';

export const KILL_LIST_PROBLEMS: Problem[] = [
  {
    "id": "k_1",
    "name": "Successive Percentage Increment",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Percentages",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_2",
    "name": "Election Voting Margin",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Percentages",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_3",
    "name": "Population Growth Formula",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Percentages",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_4",
    "name": "Machine Depreciation Value",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Percentages",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_5",
    "name": "Price/Consumption Inverse Check",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Percentages",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_6",
    "name": "Pass/Fail Exam Marks",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Percentages",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_7",
    "name": "Fraction to Percentage Core",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Percentages",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_8",
    "name": "Salary Allocation Logic",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Percentages",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_9",
    "name": "Tax Computation Check",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Percentages",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_10",
    "name": "Error in Measurement %",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Percentages",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_11",
    "name": "Dishonest Dealer (Faulty Weight)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Profit & Loss",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_12",
    "name": "Successive Discount Logic",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Profit & Loss",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_13",
    "name": "Marked Price vs Cost Price",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Profit & Loss",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_14",
    "name": "Buy X Get Y Free %",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Profit & Loss",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_15",
    "name": "Profit on Selling Price",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Profit & Loss",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_16",
    "name": "Mixture Selling for Profit",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Profit & Loss",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_17",
    "name": "Two Items Same SP, Different CP",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Profit & Loss",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_18",
    "name": "Dealer Cheating on Buy & Sell",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Profit & Loss",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_19",
    "name": "Partnership Investments",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Ratio & Proportion",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_20",
    "name": "Coin Denominations",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Ratio & Proportion",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_21",
    "name": "Income/Expenditure Difference",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Ratio & Proportion",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_22",
    "name": "Adding Liquid to Mixture Ratio",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Ratio & Proportion",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_23",
    "name": "Age Ratio After N Years",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Ratio & Proportion",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_24",
    "name": "Third & Fourth Proportional",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Ratio & Proportion",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_25",
    "name": "Distributing Money Unequally",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Ratio & Proportion",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_26",
    "name": "Diamond Breakdown Weight Ratio",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Ratio & Proportion",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_27",
    "name": "Replacement of Member",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Average",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_28",
    "name": "Batting Average Change",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Average",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_29",
    "name": "Weighted Class Average",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Average",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_30",
    "name": "Average Velocity",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Average",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_31",
    "name": "Faulty Readings Correction",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Average",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_32",
    "name": "Mixing Two Price Items",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Mixture & Allegation",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_33",
    "name": "Pure Liquid Replacement Iterations",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Mixture & Allegation",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_34",
    "name": "Alloy Composition",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Mixture & Allegation",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_35",
    "name": "Profit mixing cheap and expensive",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Mixture & Allegation",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_36",
    "name": "Water added to reduce concentration",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Mixture & Allegation",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_37",
    "name": "Pipes & Cisterns Inlets/Outlets",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Time & Work",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_38",
    "name": "Alternating Days Logic",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Time & Work",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_39",
    "name": "Men leaving after X days",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time & Work",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_40",
    "name": "Efficiency Ratios (A is twice B)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Time & Work",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_41",
    "name": "Man Days Work Formula",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time & Work",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_42",
    "name": "Contractor Delays",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time & Work",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_43",
    "name": "Wage Distribution based on Work",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time & Work",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_44",
    "name": "Relative Speed (Opposite Trains)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Time Speed Distance",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_45",
    "name": "Relative Speed (Same Direction)",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time Speed Distance",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_46",
    "name": "Boats Upstream/Downstream",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Time Speed Distance",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_47",
    "name": "Meeting at a point (Early/Late)",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time Speed Distance",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_48",
    "name": "Races & Linear Tracks",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time Speed Distance",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_49",
    "name": "Circular Tracks meeting point",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time Speed Distance",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_50",
    "name": "Bullet Firing Sound Delay",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Time Speed Distance",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_51",
    "name": "Divisibility by 7, 11, 13",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Number System",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_52",
    "name": "HCF word problems (Largest size)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Number System",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_53",
    "name": "LCM word problems (Bells tolling)",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_54",
    "name": "Remainder Theorem Basics",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Number System",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_55",
    "name": "Fermat & Wilson Theorem Check",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_56",
    "name": "Find Unit Digit of a^b",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Number System",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_57",
    "name": "Find Last Two Digits",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_58",
    "name": "Trailing Zeros in Factorial",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_59",
    "name": "Number of Factors of N",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_60",
    "name": "Sum of Factors of N",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_61",
    "name": "Prime Factorization Logic",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_62",
    "name": "Base Coversion (Binary/Decimal)",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_63",
    "name": "Successive Division",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_64",
    "name": "Finding the Missing Digit for factor",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_65",
    "name": "Cyclicity of Powers",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Number System",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_66",
    "name": "Linear equation in 2 variables",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_67",
    "name": "Age Problems (Past vs Future)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_68",
    "name": "Quadratic Roots Sum/Product",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_69",
    "name": "Discriminant Nature of Roots",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_70",
    "name": "BODMAS Simplification Fast Trick",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_71",
    "name": "Fractions Comparison",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_72",
    "name": "Surds & Indices Core Laws",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_73",
    "name": "Surds Rationalization",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_74",
    "name": "Logarithm Addition Rule",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_75",
    "name": "Logarithm Base Change",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_76",
    "name": "AP (Arithmetic Progression) Nth term",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_77",
    "name": "AP Sum of N terms",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_78",
    "name": "GP Nth term",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_79",
    "name": "Infinite GP Sum",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_80",
    "name": "Max/Min of Quadratic Equation",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Quant: Algebra & Misc",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_81",
    "name": "Letter Shifting (Vowels vs Consonants)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Coding-Decoding",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_82",
    "name": "Number to Letter Substitution",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Coding-Decoding",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_83",
    "name": "Matrix Coding",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Coding-Decoding",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_84",
    "name": "Symbolic Coding Logic",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Coding-Decoding",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_85",
    "name": "Word Replacement (If Apple is Blue...)",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Coding-Decoding",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_86",
    "name": "Pointing to a Photograph",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Blood Relations",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_87",
    "name": "Coded Relations (A+B means father)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Blood Relations",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_88",
    "name": "Family Tree Puzzle",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Blood Relations",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_89",
    "name": "Jumbled Generation Map",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Blood Relations",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_90",
    "name": "Indirect Relation Chase",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Blood Relations",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_91",
    "name": "Shadow Direction at Sunrise/Sunset",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Direction Sense",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_92",
    "name": "Pythagoras Shortest Path",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Direction Sense",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_93",
    "name": "Continuous Left/Right Rotation",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Direction Sense",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_94",
    "name": "Clockwise Degree Turns",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Direction Sense",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_95",
    "name": "Relative Position Mapping",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Direction Sense",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_96",
    "name": "Linear Facing North",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_97",
    "name": "Linear Facing North/South Mixed",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_98",
    "name": "Circular Facing Center",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_99",
    "name": "Circular Facing Away",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_100",
    "name": "Square Table Middle/Corner",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_101",
    "name": "Two Parallel Rows",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_102",
    "name": "Circular with Variables (Blood + Seating)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_103",
    "name": "Linear with Height order",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_104",
    "name": "Floor Based Puzzle",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_105",
    "name": "Box Stack Puzzle",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Seating Arrangement",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_106",
    "name": "All A are B, Some B are C",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Syllogism",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_107",
    "name": "Possibility Cases (Can be)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Syllogism",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_108",
    "name": "Only a few logic",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Syllogism",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_109",
    "name": "Neither/Nor Cases",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Syllogism",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_110",
    "name": "Reverse Syllogism",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Syllogism",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_111",
    "name": "Missing Number (Difference of Difference)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Series",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_112",
    "name": "Prime Number Logic Jumps",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Series",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_113",
    "name": "Alpha-Numeric Sequence",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Series",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_114",
    "name": "Continuous Pattern Series (aba_c_)",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Series",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_115",
    "name": "Wrong Number in Series",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Series",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_116",
    "name": "Numeric Logic Exclusions",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Logical: Odd One Out",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_117",
    "name": "Word Semantics Anomalies",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Odd One Out",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_118",
    "name": "Cube/Square deviations",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Odd One Out",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_119",
    "name": "Alphabetical gap mismatch",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Odd One Out",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_120",
    "name": "Diagrammatic reasoning anomalies",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Logical: Odd One Out",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_121",
    "name": "Scientific Passage Tone Inference",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_122",
    "name": "Historical Passage Fact Check",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_123",
    "name": "Author Purpose Identification",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_124",
    "name": "Main Idea Extraction",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_125",
    "name": "Specific Detail Hunt",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_126",
    "name": "Vocabulary in Context (RC)",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_127",
    "name": "Logical Flow Inference",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_128",
    "name": "Sarcasm/Irony Detection",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_129",
    "name": "Title Recommendation",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_130",
    "name": "True/False Exception Finding",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Reading Comprehension",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_131",
    "name": "High-frequency GRE word matching",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Verbal: Synonyms/Antonyms",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_132",
    "name": "Contextual root prefixes",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Synonyms/Antonyms",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_133",
    "name": "Negative prefix identifiers",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Synonyms/Antonyms",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_134",
    "name": "Euphemism replacements",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Synonyms/Antonyms",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_135",
    "name": "Degree of intensity adjectives",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Synonyms/Antonyms",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_136",
    "name": "Subject-Verb Agreement (Along with/As well as)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Verbal: Sentence Correction",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_137",
    "name": "Tense Inconsistencies",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Sentence Correction",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_138",
    "name": "Parallelism Structure",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Verbal: Sentence Correction",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_139",
    "name": "Modifier Placements",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Sentence Correction",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_140",
    "name": "Pronoun Antecedent Match",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Sentence Correction",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_141",
    "name": "Identify Introductory Sentence",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Verbal: Para Jumbles",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_142",
    "name": "Link Mandatory Pairs (Pronouns)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Verbal: Para Jumbles",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_143",
    "name": "Chronological Order Linking",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Para Jumbles",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_144",
    "name": "Cause and Effect Linkage",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Para Jumbles",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_145",
    "name": "Concluding Sentence Placement",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Para Jumbles",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_146",
    "name": "Preposition Collocations (Accused of, Good at)",
    "category": "Aptitude",
    "isPriority": true,
    "topic": "Verbal: Fill in the Blanks",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_147",
    "name": "Vocabulary Context Clues",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Fill in the Blanks",
    "difficulty": "Easy",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_148",
    "name": "Conjunction Linking (Although, Despite)",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Fill in the Blanks",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_149",
    "name": "Double Fillers Matching",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Fill in the Blanks",
    "difficulty": "Hard",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_150",
    "name": "Phrasal Verbs Insertion",
    "category": "Aptitude",
    "isPriority": false,
    "topic": "Verbal: Fill in the Blanks",
    "difficulty": "Medium",
    "platform": "Other",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_151",
    "name": "Two Sum",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_152",
    "name": "Kadane’s Algorithm (Max Subarray)",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_153",
    "name": "Move Zeroes",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_154",
    "name": "Best Time to Buy/Sell Stock",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_155",
    "name": "Merge Intervals",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_156",
    "name": "Rotate Array",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_157",
    "name": "Majority Element",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_158",
    "name": "Subarray Sum = K",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_159",
    "name": "Longest Consecutive Sequence",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_160",
    "name": "Container With Most Water",
    "category": "DSA",
    "isPriority": true,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_161",
    "name": "Pascal Triangle",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_162",
    "name": "Set Matrix Zeroes",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_163",
    "name": "Find Duplicate Number",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_164",
    "name": "Next Permutation",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_165",
    "name": "Sort Colors",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_166",
    "name": "Find Missing and Repeating",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_167",
    "name": "Trapping Rain Water",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_168",
    "name": "Product of Array Except Self",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_169",
    "name": "Maximum Product Subarray",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_170",
    "name": "Search in a 2D Matrix",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_171",
    "name": "Spiral Matrix",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_172",
    "name": "Count Inversions",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_173",
    "name": "Reverse Pairs",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_174",
    "name": "3Sum",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_175",
    "name": "4Sum",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_176",
    "name": "Longest Subarray with 0 Sum",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_177",
    "name": "Subarrays with XOR K",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_178",
    "name": "Majority Element II",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_179",
    "name": "Merge Two Sorted Arrays without extra space",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_180",
    "name": "Find Minimum in Rotated Sorted Array",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_181",
    "name": "Next Greater Permutation",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_182",
    "name": "Kth Largest Element",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_183",
    "name": "Find First and Last Position",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_184",
    "name": "Insert Interval",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_185",
    "name": "Non-overlapping Intervals",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_186",
    "name": "Missing Number",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_187",
    "name": "Intersection of Two Arrays",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_188",
    "name": "Find All Duplicates",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_189",
    "name": "Subarray Product Less Than K",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_190",
    "name": "Minimum Size Subarray Sum",
    "category": "DSA",
    "isPriority": false,
    "topic": "Arrays",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_191",
    "name": "Valid Palindrome",
    "category": "DSA",
    "isPriority": true,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_192",
    "name": "Anagram Check",
    "category": "DSA",
    "isPriority": true,
    "topic": "Strings",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_193",
    "name": "Longest Substring Without Repeating",
    "category": "DSA",
    "isPriority": true,
    "topic": "Strings",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_194",
    "name": "String Compression",
    "category": "DSA",
    "isPriority": true,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_195",
    "name": "Count and Say",
    "category": "DSA",
    "isPriority": true,
    "topic": "Strings",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_196",
    "name": "Implement strstr()",
    "category": "DSA",
    "isPriority": true,
    "topic": "Strings",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_197",
    "name": "Reverse Words",
    "category": "DSA",
    "isPriority": true,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_198",
    "name": "Longest Palindromic Substring",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_199",
    "name": "Group Anagrams",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_200",
    "name": "Longest Common Prefix",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_201",
    "name": "Valid Anagram",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_202",
    "name": "Find All Anagrams in a String",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_203",
    "name": "Validate IP Address",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_204",
    "name": "Rabin Karp Algorithm",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_205",
    "name": "KMP Algorithm",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_206",
    "name": "Minimum Characters to Add for Palindrome",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_207",
    "name": "Isomorphic Strings",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_208",
    "name": "Word Pattern",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_209",
    "name": "Sort Characters By Freq",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_210",
    "name": "Excel Sheet Column Title",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_211",
    "name": "Roman to Integer",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_212",
    "name": "Integer to Roman",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_213",
    "name": "Longest Repeating Character Replacement",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_214",
    "name": "Palindromic Substrings",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_215",
    "name": "Check if String is Rotated",
    "category": "DSA",
    "isPriority": false,
    "topic": "Strings",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_216",
    "name": "Factorial/Fibonacci (Memoize)",
    "category": "DSA",
    "isPriority": true,
    "topic": "Recursion+Backtrack",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_217",
    "name": "Subsets",
    "category": "DSA",
    "isPriority": true,
    "topic": "Recursion+Backtrack",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_218",
    "name": "Permutations",
    "category": "DSA",
    "isPriority": true,
    "topic": "Recursion+Backtrack",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_219",
    "name": "N-Queens",
    "category": "DSA",
    "isPriority": true,
    "topic": "Recursion+Backtrack",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_220",
    "name": "Generate Parentheses",
    "category": "DSA",
    "isPriority": true,
    "topic": "Recursion+Backtrack",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_221",
    "name": "Combination Sum",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_222",
    "name": "Combination Sum II",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_223",
    "name": "Palindrome Partitioning",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_224",
    "name": "Word Search",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_225",
    "name": "Sudoku Solver",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_226",
    "name": "Rat in a Maze",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_227",
    "name": "M-Coloring Problem",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_228",
    "name": "Subset Sum",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_229",
    "name": "Kth Permutation Sequence",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_230",
    "name": "Letter Combinations of a Phone Number",
    "category": "DSA",
    "isPriority": false,
    "topic": "Recursion+Backtrack",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_231",
    "name": "Binary Search",
    "category": "DSA",
    "isPriority": true,
    "topic": "Search & Sort",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_232",
    "name": "Lower/Upper Bound",
    "category": "DSA",
    "isPriority": true,
    "topic": "Search & Sort",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_233",
    "name": "Quick Sort (Partition)",
    "category": "DSA",
    "isPriority": true,
    "topic": "Search & Sort",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_234",
    "name": "Merge Sort",
    "category": "DSA",
    "isPriority": true,
    "topic": "Search & Sort",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_235",
    "name": "Search in Rotated Sorted Array",
    "category": "DSA",
    "isPriority": true,
    "topic": "Search & Sort",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_236",
    "name": "Find Peak Element",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_237",
    "name": "Search 2D Matrix",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_238",
    "name": "Koko Eating Bananas",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_239",
    "name": "Minimum Days to Make Bouquets",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_240",
    "name": "Allocate Minimum Number of Pages",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_241",
    "name": "Aggressive Cows",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_242",
    "name": "Capacity to Ship Packages within D Days",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_243",
    "name": "Median of Two Sorted Arrays",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_244",
    "name": "Kth Element of Two Sorted Arrays",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_245",
    "name": "Sort an Array",
    "category": "DSA",
    "isPriority": false,
    "topic": "Search & Sort",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_246",
    "name": "Reverse Linked List",
    "category": "DSA",
    "isPriority": true,
    "topic": "Linked List",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_247",
    "name": "Detect Cycle",
    "category": "DSA",
    "isPriority": true,
    "topic": "Linked List",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_248",
    "name": "Middle of Linked List",
    "category": "DSA",
    "isPriority": true,
    "topic": "Linked List",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_249",
    "name": "Merge Two Sorted Lists",
    "category": "DSA",
    "isPriority": true,
    "topic": "Linked List",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_250",
    "name": "Remove Nth Node from End",
    "category": "DSA",
    "isPriority": true,
    "topic": "Linked List",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_251",
    "name": "Palindrome Linked List",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_252",
    "name": "Intersection of Two Lists",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_253",
    "name": "Add Two Numbers",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_254",
    "name": "Reverse Nodes in k-Group",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_255",
    "name": "Copy List with Random Pointer",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_256",
    "name": "Starting Point of Loop",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_257",
    "name": "Flatten a Linked List",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_258",
    "name": "Rotate List",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_259",
    "name": "Delete Node in a Linked List",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_260",
    "name": "Sort List",
    "category": "DSA",
    "isPriority": false,
    "topic": "Linked List",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_261",
    "name": "Valid Parentheses",
    "category": "DSA",
    "isPriority": true,
    "topic": "Stack & Queue",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_262",
    "name": "Next Greater Element",
    "category": "DSA",
    "isPriority": true,
    "topic": "Stack & Queue",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_263",
    "name": "Implement Stack using Queue",
    "category": "DSA",
    "isPriority": true,
    "topic": "Stack & Queue",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_264",
    "name": "Sliding Window Maximum",
    "category": "DSA",
    "isPriority": true,
    "topic": "Stack & Queue",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_265",
    "name": "Min Stack",
    "category": "DSA",
    "isPriority": true,
    "topic": "Stack & Queue",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_266",
    "name": "Daily Temperatures",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_267",
    "name": "Evaluate Reverse Polish Notation",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_268",
    "name": "Implement Queue using Stack",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_269",
    "name": "LRU Cache",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_270",
    "name": "LFU Cache",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_271",
    "name": "Largest Rectangle in Histogram",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_272",
    "name": "Maximal Rectangle",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_273",
    "name": "Next Smaller Element",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_274",
    "name": "Stock Span Problem",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_275",
    "name": "Rotting Oranges",
    "category": "DSA",
    "isPriority": false,
    "topic": "Stack & Queue",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_276",
    "name": "Inorder/Pre/Post (Iterative)",
    "category": "DSA",
    "isPriority": true,
    "topic": "Trees",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_277",
    "name": "Level Order Traversal",
    "category": "DSA",
    "isPriority": true,
    "topic": "Trees",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_278",
    "name": "Height of Tree",
    "category": "DSA",
    "isPriority": true,
    "topic": "Trees",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_279",
    "name": "Diameter of Tree",
    "category": "DSA",
    "isPriority": true,
    "topic": "Trees",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_280",
    "name": "Lowest Common Ancestor",
    "category": "DSA",
    "isPriority": true,
    "topic": "Trees",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_281",
    "name": "Validate BST",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_282",
    "name": "Symmetric Tree",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_283",
    "name": "Maximum Depth of Binary Tree",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_284",
    "name": "Binary Tree Maximum Path Sum",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_285",
    "name": "Same Tree",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_286",
    "name": "Binary Tree Zigzag Level Order Traversal",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_287",
    "name": "Construct Tree from Inorder & Preorder",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_288",
    "name": "Serialize and Deserialize Binary Tree",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_289",
    "name": "Kth Smallest Element in BST",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_290",
    "name": "Invert Binary Tree",
    "category": "DSA",
    "isPriority": false,
    "topic": "Trees",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_291",
    "name": "Frequency Count Array",
    "category": "DSA",
    "isPriority": true,
    "topic": "Basic Hashing",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_292",
    "name": "Two Sum using HashMap",
    "category": "DSA",
    "isPriority": true,
    "topic": "Basic Hashing",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_293",
    "name": "First Non-Repeating Character",
    "category": "DSA",
    "isPriority": true,
    "topic": "Basic Hashing",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_294",
    "name": "Longest Subarray with Sum K",
    "category": "DSA",
    "isPriority": true,
    "topic": "Basic Hashing",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_295",
    "name": "Check if Array pairs are divisible by k",
    "category": "DSA",
    "isPriority": false,
    "topic": "Basic Hashing",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_296",
    "name": "Count distinct elements in every window",
    "category": "DSA",
    "isPriority": false,
    "topic": "Basic Hashing",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_297",
    "name": "Subarray with 0 sum",
    "category": "DSA",
    "isPriority": false,
    "topic": "Basic Hashing",
    "difficulty": "Hard",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_298",
    "name": "Find Itinerary from Tickets",
    "category": "DSA",
    "isPriority": false,
    "topic": "Basic Hashing",
    "difficulty": "Easy",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_299",
    "name": "Contains Duplicate II",
    "category": "DSA",
    "isPriority": false,
    "topic": "Basic Hashing",
    "difficulty": "Medium",
    "platform": "CodeVita",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  },
  {
    "id": "k_300",
    "name": "Jewels and Stones",
    "category": "DSA",
    "isPriority": false,
    "topic": "Basic Hashing",
    "difficulty": "Hard",
    "platform": "LeetCode",
    "status": "Todo",
    "notes": "",
    "addedAt": "2026-03-31"
  }
];
